name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test-cookiecutter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Test cookiecutter
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          ./scripts/test_cookiecutter.sh
